name: codium
adopt-info: codium
summary: Code editing. Redefined.
description: |
  Binary releases of Code without branding/telemetry/licensing

base: core18
grade: stable
confinement: classic
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  
apps:
  codium:
    command: electron-launch $SNAP/usr/share/codium/bin/codium
    desktop: usr/share/applications/codium.desktop
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

  url-handler:
    command: electron-launch $SNAP/usr/share/codium/bin/codium --open-url
    desktop: usr/share/applications/codium-url-handler.desktop
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

parts:
  build-trigger:
    plugin: nil
    source: https://github.com/VSCodium/vscodium.git
  codium:
    plugin: nil
    override-build: |
      set -eu
      ARCHITECTURE=$(dpkg --print-architecture)
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/VSCodium/vscodium/releases -O releases.json
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      DEB_URL=$(grep browser_download releases.json | grep "download/${VERSION}" | grep deb | grep $ARCHITECTURE | grep -v sha256 | cut -d'"' -f4 | tail -n 1)
      DEB=$(basename "${DEB_URL}")
      echo "Downloading ${DEB_URL}..."
      wget "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      echo "Unpacking ${DEB}..."
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f releases.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      snapcraftctl set-version "$VERSION"
      sed -i 's|Icon=vscodium|Icon=${SNAP}/usr/share/pixmaps/vscodium.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/codium.desktop
      sed -i 's|Exec=/usr/share/codium/codium|Exec=codium|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/codium.desktop
      sed -i 's|Icon=vscodium|Icon=/usr/share/pixmaps/vscodium.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/codium-url-handler.desktop
    build-packages:
      - wget
      - jq
    stage-packages:
      - fcitx-frontend-gtk3
      - gvfs-libs
      - libasound2
      - libgconf-2-4
      - libglib2.0-bin
      - libgnome-keyring0
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libsecret-1-0
      - libxss1
      - libxtst6
      - zlib1g
      - libx11-xcb1
      - libxkbfile1
      - libdrm2
      - libgbm1
      - libxcb-dri3-0
    prime:
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/codium/chrome-sandbox
  wrapper:
    after:
      - codium
    plugin: dump
    source: snap/local
